---
abstract: 'GUI wrapper for command line scripts and programs'
author:
  - 'Reid Augustin <reid@hellosix.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CLI-Gwrap
requires:
  Carp: 0
  Dancer: 0
  Exporter: 0
  File::Spec: 0
  IO::File: 0
  IPC::Run: 0
  Moo: 1.000
  Moo::Role: 0
  Readonly: 0
  Scalar::Util: 0
  Types::Standard: 0
  Wx: 0
  Wx::App: 0
  Wx::Event: 0
  perl: 5.008
  strict: 0
  warnings: 0
version: 0.026
